### ISSUE TITLE
Ubuntu packaging - /usr/.crates2.json included

### ISSUE THREAD

**Issue by filimonov** [sharkdp/hexyl#126]
Ubuntu 20.04

I don't think it was included intentionally.

```
dpkg: error processing archive /var/cache/apt/archives/hexyl_0.6.0-2build1_amd64.deb (--unpack):
 trying to overwrite '/usr/.crates2.json', which is also in package ripgrep 11.0.2-1build1
```

**Comment by filimonov** [comment]
w/o
https://bugs.launchpad.net/ubuntu/+source/rust-bat/+bug/1868517/comments/32

**Comment by sharkdp** [comment]
Yes, that's really unfortunate. See related ticket here: https://github.com/sharkdp/bat/issues/938

Unfortunately, there is nothing we can do about it here.

**Comment by filimonov** [comment]
> there is nothing we can do about it here.

How do you package hexyl into deb? Can't you just exclude the file from the package?

**Comment by sharkdp** [comment]
The Debian/Ubuntu maintainers are doing that. Not me. This has to be fixed in Ubuntu (you linked to the ticket yourself).

We also build Debian packages here in this repository: https://github.com/sharkdp/hexyl/releases/tag/v0.8.0 - but you cannot install them with `apt-get`. You have to download them manually and then use `dpkg` to install. They should not have that problem.

**Comment by filimonov** [comment]
ARAIR i was picking the deb build from releases page. But don't remember right now and will not check it.

I'm ok to close the issue.

**Comment by sharkdp** [comment]
> But don't remember right now and will not check it.

It's easy to see from the `.deb` name and the file system path that these are NOT the packages that we build here. Those are the Ubuntu packages.
