### ISSUE TITLE
--version prints newline to stderr

### ISSUE THREAD

**Issue by ehandal** [sharkdp/hexyl#131]
This is a bit weird, not sure if intentional:

```
~ $ hexyl --version
hexyl 0.8.0
~ $ hexyl --version > /dev/null

~ $ hexyl --version &> /dev/null
~ $
```

**Comment by sharkdp** [comment]
That is not intended, no. Thanks for reporting.

**Comment by scimas** [comment]
There isn't any newline in the version output. See clap-rs/clap#1960, clap-rs/clap#1972 which will actually (correctly) __add__ new lines to the version output.

The reason hexyl is getting a newline on `stderr` is this:
`clap` prints version for hexyl __without__ the trailing newline (the PR I linked above isn't included in the clap version hexyl is built with). But then the `eprint!` in hexyl [main](https://github.com/sharkdp/hexyl/blob/642eff606132c3626e6e0d63e6c2802491252279/src/bin/hexyl.rs#L238) calls the [error formatting](https://github.com/clap-rs/clap/blob/ffb8d552c2e9a49da50d93577345779fb92c34a1/src/errors.rs#L902-L906) in clap which does a `writeln!` and so you get the newline in `stderr`.

For some reason the `--help` output is directed to `stderr` rather than `stdout`, so the issue isn't visible there.
