### ISSUE TITLE
hexyl output fail when piped through more

### ISSUE THREAD

**Issue by mhewett-ks** [sharkdp/hexyl#32]
<img width="1269" alt="hexyl-more-fail-2019-01-11" src="https://user-images.githubusercontent.com/45076465/51049205-0aa49200-1582-11e9-8d9d-9459e23a7bc3.png">

This is on Mac OS 10.14.2 in the bash shell.  
Installed today with 'brew install hexyl'

**Comment by kilobyte** [comment]
This is a case of #30 — many tools are not capable of accepting ANSI codes.

Besides, may I ask why do you even use ``more`` this millenium?  It has been obsoleted by ``less`` mere 35 years ago.  But even ``less`` doesn't default to accepting ANSI, you need to specify ``less -R``.

The core issue is real; almost all other programs won't write color when redirected.  It's debatable only because ``hexyl``'s value is the coloring — without it, you're probably better off using ``hd`` instead, as the latter can do anything that *hexyl* can, plus more.  But then, most of ``hd``'s features are pointless these days.

**Comment by sharkdp** [comment]
Let's continue this discussion in #30.
